#!/bin/bash
# -----------------------------------------------------------------------------
# docker /start script
# -----------------------------------------------------------------------------

/bin/sed -i "s/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, $NAGIOS_SERVER/g" /etc/nagios/nrpe.cfg

/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -d

# Run supervisor that in turn run the servers
/usr/bin/supervisord -n
